### ISSUE TITLE
link to julianlsolvers fails

### ISSUE THREAD

**Issue by RossBoylan** [JuliaNLSolvers/NLSolversBase.jl#103]
2nd line of README.md, as displayed on the web, is 
NLSolversBase.jl is the core, common dependency of several packages in the JuliaNLSolvers family.

That includes a link to https://julianlsolvers.github.io/ which produces a "site not  found" 404 error.

**Comment by pkofod** [comment]
Thanks, I changed it to https://github.com/JuliaNLSolvers/.
