### ISSUE TITLE
TwiceDifferentiable

### ISSUE THREAD

**Issue by lbittarello** [JuliaNLSolvers/NLSolversBase.jl#12]
Since I updated, `TwiceDifferentiable(f, g!, fg!, h!)` fails. I must either omit `fg!` or add a seed vector. I think a method is missing around line 95 in [objective_types.jl](https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/master/src/objective_types.jl).

**Comment by pkofod** [comment]
Thanks, should work if you checkout master now. Is there a specific reason why you do not want to provide a seed upfront?

**Comment by lbittarello** [comment]
Thanks!

I don't mind providing a seed. However, the (outdated) documentation of Optim doesn't mention seeds and neither `TwiceDifferentiable(f, g!, h!)` nor `OnceDifferentiable(f, g!, fg!)` need one, so it seemed to me that the inconsistency was unintentional.

**Comment by pkofod** [comment]
> However, the (outdated) documentation of Optim doesn't mention seeds

That is certainly not intentional.

> so it seemed to me that the inconsistency was unintentional.

It was.

**Comment by pkofod** [comment]
I see that we're going to need a patch for this thing in OptimBase.

**Comment by pkofod** [comment]
https://github.com/JuliaNLSolvers/Optim.jl/pull/427

**Comment by pkofod** [comment]
@lbittarello If you `Pkg.update()` now, it should work!

**Comment by lbittarello** [comment]
Like a charm! Thanks a bunch!
