### ISSUE TITLE
Slow loading

### ISSUE THREAD

**Issue by jebej** [JuliaNLSolvers/NLSolversBase.jl#135]
This package is slow to load due to its dependence on FiniteDiff and ForwardDiff. This is somewhat problematic given it should be a "lightweight" base package, especially if packages above it do not need the functionality.

```julia
julia> @time using NLSolversBase
  9.662709 seconds (14.06 M allocations: 740.722 MiB, 3.58% gc time)
```

**Comment by pkofod** [comment]
Well, it's not meant to be light weight. It provides AD as one if its features for Optim *and* NLsolve *and* LsqFit. However, if you look at NLSolvers.jl which is the new backend code for Optim, you will see that I specifically left out AD for this reason. Then, Optim will include AD and NLSolvers.jl will not. So if you really need something cheap, you can use NLSolvers.jl
