### ISSUE TITLE
allow using other array types in TwiceOrderDifferentiable finite differences

### ISSUE THREAD

**Issue by longemen3000** [JuliaNLSolvers/NLSolversBase.jl#139]
xref https://github.com/JuliaNLSolvers/Optim.jl/issues/924

**Comment by amrods** [comment]
Is this as easy as changing `Vector` to `AbstractVector` and `Matrix` to `AbstractMatrix` in https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/62d2199f70cce78479658da08d346bbc060fc2f7/src/objective_types/twicedifferentiable.jl#L116 ? If so, I can make that PR. I am needing that relatively quickly.

**Comment by longemen3000** [comment]
Yes, it's only that. If you need it right know without waiting for a PR, you can write a junction yourself that does what the Twicedifferentiable.jl constructor do

**Comment by amrods** [comment]
I'll do that in my fork directly, but I won't make a PR. I don't want to usurp it from you. I am afraid of messing up my packages though. I suppose I can remove the "official" version and instead install my fork.
