### ISSUE TITLE
Deprecations and femtocleaner

### ISSUE THREAD

**Issue by pkofod** [JuliaNLSolvers/NLSolversBase.jl#16]
att @keno : I am wondering if FemtoCleaner shouldn't have removed https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/ddd6847e84116ad1fad258bbb066e5a298265c49/REQUIRE#L2 https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/ddd6847e84116ad1fad258bbb066e5a298265c49/src/objective_types.jl#L1 and https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/ddd6847e84116ad1fad258bbb066e5a298265c49/src/NLSolversBase.jl#L5 ?

**Comment by Keno** [comment]
Looks like it did remove the `@compat`? It doesn't touch REQUIREs or imports, because those have non-syntactic effects that it can't be sure about.

**Comment by pkofod** [comment]
> Looks like it did remove the @compat? It doesn't touch REQUIREs or imports, because those have non-syntactic effects that it can't be sure about.

That's weird! I searched the repo for `compat` *just* before opening the issue and I found those three occurrences. Oh well, thanks!
