### ISSUE TITLE
Hessian-vector products

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/NLSolversBase.jl#23]
JuliaNLSolvers/Optim.jl#416 is waiting for Hessian-vector product support in NLSolversBase, it seems (https://github.com/JuliaNLSolvers/Optim.jl/pull/416#issuecomment-307898009 )

Just adding this issue to keep track of TODOs

**Comment by pkofod** [comment]
Yes, I’m a aware. I’m talking to Ryan Tuesday, and I think I’ll suggest a solution after that.
