### ISSUE TITLE
`@inline` getters

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/NLSolversBase.jl#26]
E.g. https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/master/src/interface.jl#L59

**Comment by pkofod** [comment]
I would have thought they were inlined. Is this "just because" or is it just to avoid the function call? :)

**Comment by anriseth** [comment]
It's "just in case", even though it's most likely inlined already ;)

**Comment by pkofod** [comment]
I'm pretty sure we should just let this be up to the compiler.
