### ISSUE TITLE
Jacobian dimensions are wrong

### ISSUE THREAD

**Issue by mohamed82008** [JuliaNLSolvers/NLSolversBase.jl#39]
https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/3923f847b55fbff56d250f63aab754a2ed452486/src/objective_types/abstract.jl#L21

The Jacobian is not nxn, it's mxn where m is the number of functions, or you can store its nxm transpose depending on how you want to iterative over it.

**Comment by mohamed82008** [comment]
Also it doesn't consider the complex case.

**Comment by pkofod** [comment]
You're correct if you consider a larger class of problems than we do. Is it to accommodate least squares problems, or what do you have in mind? I actually thought of changing it exactly to make it work with levenberg-marquardt in lsqfit

**Comment by mohamed82008** [comment]
I was merely entertaining the possibility with no use case in mind, just for sake of generality since you already have F input, and there seems to be a direction to accommodate complex number optimization.

**Comment by pkofod** [comment]
Ah okay, yeah we can change it.

**Comment by mohamed82008** [comment]
I am also a bit weary of initializing derivatives or Jacobians with 0, since any algorithm bug which checks for convergence criteria first thing in a while loop for example may assume the algorithm has converged. I think this can be one less thing to keep in mind if it is initialized to `NaN`s or something.

**Comment by pkofod** [comment]
not anymore

**Comment by mohamed82008** [comment]
Awesome!

**Comment by pkofod** [comment]
:)
