### ISSUE TITLE
Weird/wrong syntax for NonDifferentiable struct definition

### ISSUE THREAD

**Issue by mohamed82008** [JuliaNLSolvers/NLSolversBase.jl#40]
https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/3923f847b55fbff56d250f63aab754a2ed452486/src/objective_types/nondifferentiable.jl#L2

The syntax here looks off, am I missing something?

**Comment by pkofod** [comment]
The `where` part?

**Comment by mohamed82008** [comment]
Yes.
