### ISSUE TITLE
Why is f_calls not the same shape as F?

### ISSUE THREAD

**Issue by mohamed82008** [JuliaNLSolvers/NLSolversBase.jl#41]
https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/3923f847b55fbff56d250f63aab754a2ed452486/src/objective_types/nondifferentiable.jl#L27

The same thing is there with other objective types.

**Comment by pkofod** [comment]
What do you mean ? f_calls is a counter, why would they be related?

**Comment by mohamed82008** [comment]
Oh ok because it is a vector in a mutable, so I  thought it must be 1 counter for each objective or something. But I realize all the objectives are computed by the same function `f` so this has to be only 1 number. But then there is no need for it to be a vector because the struct is mutable.

**Comment by pkofod** [comment]
I wonder if it wasn't earlier. Hmm

**Comment by mohamed82008** [comment]
Closing this issue.
