### ISSUE TITLE
Sorting out f, df and fdf handling in incomplete.jl and abstract.jl

### ISSUE THREAD

**Issue by mohamed82008** [JuliaNLSolvers/NLSolversBase.jl#42]
I have a few issues with incomplete.jl.
1. It introduces a parallel way to define f, df and fdf which I think can be merged with abstract.jl.
2. It defines an inplace version of make_f when it doesn't make sense, for example in https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/3923f847b55fbff56d250f63aab754a2ed452486/src/objective_types/incomplete.jl#L32
3. The interface of fdf in terms of how many arguments and return types is inconsistent for example https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/3923f847b55fbff56d250f63aab754a2ed452486/src/objective_types/incomplete.jl#L39 and https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/3923f847b55fbff56d250f63aab754a2ed452486/src/objective_types/incomplete.jl#L46.

**Comment by pkofod** [comment]
I have to be at a computer to comment on 2. but I think some more comments may be a good idea in these files.

**Comment by mohamed82008** [comment]
I am still awed by the structure of Optim and NLSolversBase, so I would very much appreciate more comments.

**Comment by mohamed82008** [comment]
I think this https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/3923f847b55fbff56d250f63aab754a2ed452486/src/objective_types/incomplete.jl#L32 looks like a bug. `fdf(t)(F, nothing, x)` is supposed to return (F,DF) so the resulting `f` will not just return F, which I believe is assumed elsewhere such as: https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/3923f847b55fbff56d250f63aab754a2ed452486/src/objective_types/incomplete.jl#L42 and in abstract.jl because f and df will be separately by the user and f cannot be expected to return (F,DF).

**Comment by pkofod** [comment]
I think you're misunderstanding the context, but I'll try to clarify when at a computer

**Comment by mohamed82008** [comment]
I am not sure what I am misunderstanding since it seems clear that `obj.f` must return `F` only from lines like `obj.F = obj.f(real_to_complex(obj, x))` in interface.jl. Will probably continue reading tomorrow though.

**Comment by pkofod** [comment]
Still think this is working as intended, happy to reopen if someone posts a counter example (show me code that runs and does something incorrectly).
