### ISSUE TITLE
value! function is not specialized for Real and Vector TF in interface.jl

### ISSUE THREAD

**Issue by mohamed82008** [JuliaNLSolvers/NLSolversBase.jl#43]
https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/3923f847b55fbff56d250f63aab754a2ed452486/src/interface.jl#L4
This function assumes the `f` function is always non-mutating. But in the case of `TF<:AbstractVector`, this may not be true and even if true, will cause allocations.

**Comment by pkofod** [comment]
There's a specialized version for the vector case below? What do you mean it allocates?

**Comment by mohamed82008** [comment]
Oh sorry, I should have read more then. I was referring to obj.f potentially allocating if it returns a vector values, but multiple dispatch will not make this happen because of the other function. Closing the comment.

**Comment by pkofod** [comment]
We could specialize on <: Number if it helps readability! Feel free to PR
