### ISSUE TITLE
Shall we make `Abstract*Differentiable`s?

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/NLSolversBase.jl#69]
I was wondering if there would be some value to having abstract differentiable objects.
Something like this:
```jl
AbstractTwiceDifferentiable <: AbstractOnceDifferentiable <: AbstractNonDifferentiable <: AbstractObjective
TwiceDifferentiable <: AbstractTwiceDifferentiable 
OnceDifferentiable <: # etc.
```

This could possibly make dispatch easier, for example with `FMinbox` dispatching on
`AbstractOnceDifferentiable`, and hence allowing people to use `TwiceDifferentiable` (I'm not sure why they would want to, but whatever)

**Comment by pkofod** [comment]
I'm sort of afraid that this will only make it more complicated.
