### ISSUE TITLE
1.0 development

### ISSUE THREAD

**Issue by kkmann** [JuliaNLSolvers/NLSolversBase.jl#94]
Hi,

sorry for the dumb question (cf. https://discourse.julialang.org/t/guide-for-contributing-to-julia-package-on-github/17401) but I seem to be unable to figure out how to properly handle PRs and development with 1.0 + Pkg3. I forked and cloned the repo but `activate .` does not allow me to run the tests in the local instance of the repo since there is no Project.toml file (still runs the tests in .julia/... of the unmodified version) - is that intentional, am I missing something here? Thought the Project.toml was absolutely necessary.... I'd like to add a simple forward diff convenience call for `TwiceDifferentiableConstraints()` (cf. https://github.com/JuliaNLSolvers/Optim.jl/issues/609#issue-327493532)

**Comment by pkofod** [comment]
Thanks for working on this :) let’s wait to see if some of the doc gurus answer on discourse !

**Comment by pkofod** [comment]
Please do contribute those convenience functions, but this issue seems to have entered hibernation .
