### ISSUE TITLE
Higher dimensionnal Hessian

### ISSUE THREAD

**Issue by Magalame** [JuliaNLSolvers/NLSolversBase.jl#96]
Hi,

I was wondering if there was a convenient way to produce an array (of size `m` ) of `n*n` Hessian matrices for an `R^n -> R^m` vector field out of `TwiceDifferentiable`.

Thanks!

**Comment by pkofod** [comment]
Opened and closed in less than 12 hours. Did you come to a conclusion? :)

**Comment by Magalame** [comment]
Sorry I should have explained!

I didn't see any "nice" way to play around `TwiceDifferentiable` so I went straight for the `ForwardDiff` interface, with some success actually: https://github.com/JuliaDiff/ForwardDiff.jl/issues/382

I think I got a working function to compute the directional second derivative, but it still needs to get optimized. :)
